### ISSUE TITLE
question: where to load proto file in client project 

### ISSUE THREAD

**Issue by BraveShadow** [khacminh/grpc-js-healthcheck#2]
Hi there, I would like to confirm that I have to copy your `healthcheck.proto` file to my client project when I use the npm package `grpc-js-health-check` in server project, right?

**Comment by khacminh** [comment]
@BraveShadow 

You don't have to add the `healthcheck.proto` file because it follow the [GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md), so the proto file is already included. What you have to do are:

1. Import the service
2. Define a status map
3. Add it to your server


```js
const { servingStatus, Implementation, service } = require('grpc-js-health-check');

const statusMap = {
  'ServiceFoo': servingStatus.SERVING,
  'ServiceBar': servingStatus.NOT_SERVING,
  '': servingStatus.NOT_SERVING,
};
const controllers = new Implementation(statusMap);

// Now, add it to your gRPC server:
server.addService(service, controllers);

// If your app is un-healthy, you can update the healthcheck status as
controllers.setStatus(ServiceFoo, servingStatus.NOT_SERVING); // for example, ServiceFoo is un-healthy
controllers.setStatus('', servingStatus.NOT_SERVING);

```

---

I also implemented a library named [ugrpc](https://www.npmjs.com/package/ugrpc) for the gRPC communication between services. But still not add the README yet.

**Comment by BraveShadow** [comment]
👍  Thank you for the detailed instructions. I've done these steps you metioned in serve side, but the question arise on the **_client side_**. 😕 

When I create grpc client, like operations in your test code below, I need to load the proto file. So here comes the question, I don't know the value of **_protoPath_** if I don't add the `healthcheck.proto` file to my client side project.
https://github.com/khacminh/grpc-js-healthcheck/blob/66ec78c3d88ee7bed7d4673475c3ca3074ba08b1/test/client_helper.js#L7-L29
----------
> You don't have to add the healthcheck.proto file because it follows the [GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md), so the proto file is already included.

I saw your explaining above, do you mean that the proto file is already in my project, then what's the value of `protoPath`, looking forward to your reply. 🤝 

----------
I'll focus on the library you mentioned.

**Comment by khacminh** [comment]
@BraveShadow 

You can get the health check proto file from [here](https://github.com/grpc/grpc/blob/master/doc/health-checking.md)

**Comment by BraveShadow** [comment]
@khacminh Ok, much appreciated!
